version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static_data:/vol/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static_data:
