# This workflow builds and push an image of the main branch code upon validated PR

name: CI docker image

on:
  workflow_run:
    branches: "main"
    workflows: ["CI build"]
    types: 
      - completed

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build .