# This workflow creates a PR after test validation if running on the development branch

name: CI pull request

on:
  workflow_run:
    branches: "development"
    workflows: ["CI build"]
    types: 
      - completed

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: PR commit message
            title: PR title
            body: PR body
            base: development
            branch: main