# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Lint with flake8
      working-directory:
        app
      run: |
        # stop the action if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 99 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=99 --statistics

    - name: Test with pytest
      working-directory:
        app
      run: |
        pytest -v --cov


  release:
    needs: build
    name: Create PR Release to Main
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      run: |
        gh pr merge