# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: Cloud - Update available list
            title: Cloud - Update available list
            body: Cloud - Update available list
            base: main
            labels: automated-pr, Clouds & Regions
            branch: cloud-update-advanced-params
            delete-branch: true